### PR TITLE
Optionally send trace id in log

### PR DESCRIPTION
**Pull request by daveallie**
Add a boolean flag to the constructor defining whether to send the trace id to Logentries. Is enabled by default.

### CODE REVIEW

**Review by insearching — COMMENTED** [review]
Why it's not implemented?

**Comment by udangel-r7** [comment]
Because there were merge conflicts at review time. 

le_android is no longer actively supported, I.e. all merge requests and issues which couldn't get applied were closed to reflect reality.

**Comment by daveallie** [comment]
@insearching @udangel-r7 Would be happy to rebase this and make it merge-able. Just lost interest in the project at the time the PR was closed.

**Comment by insearching** [comment]
I need to remove this traceId and timestamp from logs. can you suggest how to perform it?

**Comment by udangel-r7** [comment]
@insearching please open a support request and send an email to support@logentries.com

**Comment by daveallie** [comment]
Actually I take back my previous statement, I really don't want to add another flag to the initialisation method, it is already 8 or 9 arguments long. The initialisation would really benefit from the builder pattern for defining the settings.

It would also make adding new settings a lot easier.

@insearching, for now, probably the best course of action is to open an issue.

**Pull request closed without merging**
